services:
  dev:
    image: debian:12
    container_name: jhin
    hostname: jhin
    privileged: true
    volumes:
      - ./scripts:/scripts
    stdin_open: true
    tty: true
    command: ["/bin/bash", "/scripts/main.sh"]
    restart: unless-stopped
